sudo: required
services:
   - docker

before_install:
   - docker build -t mtandur/docker-react -f ./client/Dockerfile.dev ./client


script:
   - docker run -e CI=true mtandur/docker-react npm test -- --coverage

# Generate docker images for client, nginx, server and worker
after_success:
   - docker build -t mtandur/multi-client ./client
   - docker build -t mtandur/multi-nginx ./nginx
   - docker build -t mtandur/multi-server ./server
   - docker build -t mtandur/multi-worker ./worker

   # Docker login to Docker CLI
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

   # Take these images and push to the docker hub
   - docker push mtandur/multi-client
   - docker push mtandur/multi-nginx
   - docker push mtandur/multi-server
   - docker push mtandur/multi-worker

