sudo: required
services:
   - docker

before_install:
   - docker build -t mtandur/docker-react -f ./client/Dockerfile.dev ./client

script:
   - docker run -e CI=true mtandur/docker-react npm test -- --coverage

after_success:
   - docker build -t mtandur/multi-client ./client
   - docker build -t mtandur/multi-client ./nginx
   - docker build -t mtandur/multi-client ./server
   - docker build -t mtandur/multi-client ./worker
